### ISSUE TITLE
Web - Players can start playing before everyone has selected and returned their opening destination card hand.

### ISSUE THREAD

**Issue by Bobleyl** [byucs340ta/Spring2019#18]

**Comment by bryantmh** [comment]
I wouldn't say this is a problem. But if the other game receives the draw destination cards command. It's window is overwritten and they never get to do the initial discard. So that for sure needs fixing.

**Comment by bryantmh** [comment]
@hectorlj You can close this now. It still lets one player take their first turn before the other is done discarding, but that no longer affects the other player negatively
