### ISSUE TITLE
Web - when claiming with pink : "choose a valid color" 

### ISSUE THREAD

**Issue by Bobleyl** [byucs340ta/Spring2019#21]
when trying to do using purple instead same bug

**Comment by bryantmh** [comment]
I'm not sure I get this one either. Maybe a screenshot?

**Comment by Bobleyl** [comment]
AFK, but what happened was I tried claiming a pink route with pink cards and it replied after typing "pink", "choose a valid color".   So I tried "purple" thinking you all might have given it that color instead and it said, "choose a valid color".

**Comment by bryantmh** [comment]
Oh, I got it. We should probably change the design of that to be a dropdown. Though I was unable to replicated the issue when typing purple.

**Comment by hectorlj** [comment]
Dropdowns can't be added to alerts, we'd either have to create a modal or another view. For now I'm just going to add a list to the text in the alert that says what colors are valid.

**Comment by hectorlj** [comment]
alert now has colors in it that are considered valid
