### ISSUE TITLE
Web - placeholder blue must be deleted then typed again if I want to use blue to claim route

### ISSUE THREAD

**Issue by Bobleyl** [byucs340ta/Spring2019#22]

**Comment by bryantmh** [comment]
I'm not sure I understand this one. Could you elaborate?

**Comment by Bobleyl** [comment]
When it prompts you to select the color you want to claim a gray route with it starts out with "blue" already in the box.  In order to claim using a blue route however you have to first delete the placeholder "blue" text and then type out "blue" again.

**Comment by hectorlj** [comment]
removed placeholder
