### ISSUE TITLE
Web - "Not enough rainbow cards!" when sufficient colored cards were in hand

### ISSUE THREAD

**Issue by Bobleyl** [byucs340ta/Spring2019#26]

**Comment by Bobleyl** [comment]
Omaha to chicago

**Comment by GraysonBennion** [comment]
I got a similar response here when trying to claim San Francisco to Los Angeles
![image](https://user-images.githubusercontent.com/28714656/59132030-49702580-8931-11e9-933c-a9dfe69ea4c1.png)

**Comment by bryantmh** [comment]
I've tested this and it only seems to affect purple and red routes. Though it's possible I missed one. Classifying as a backend issue with ClaimRoute. Here's the stack trace:

{"title":"Error in Command","message":"Not enough rainbow cards!","stackTrace":"java.lang.Exception: Not enough rainbow cards!\n\tat ticket_to_ride.Game.ClaimRoute(Game.java:440)\n\tat ticket_to_ride.commands.turn_commands.ClaimRouteCommand.execute(ClaimRouteCommand.java:24)\n\tat ticket_to_ride.commands.turn_commands.BaseTurnCommand.Execute(BaseTurnCommand.java:22)\n\tat

**Comment by bryantmh** [comment]
@hectorlj This has been fixed, tested, and pushed to our repo. So it can be closed.
