### ISSUE TITLE
Web - Player 1 able to draw from destination card deck before all players have chosen their destination cards

### ISSUE THREAD

**Issue by GraysonBennion** [byucs340ta/Spring2019#34]
As player 1 I was able to choose my initial destination cards and then draw more from the destination card deck before player 2 had a chance to choose their initial destination cards. On top of that it remained player 1s turn even after I had drawn that second batch of destination cards.
![image](https://user-images.githubusercontent.com/28714656/59132628-f5664080-8932-11e9-893a-8a1482aa394a.png)

**Comment by bryantmh** [comment]
Duplicate / related to this bug:
https://github.com/byucs340ta/Spring2019/issues/18

**Comment by GraysonBennion** [comment]
My bad, I'll put this over there
