### ISSUE TITLE
Web - Claiming routes

### ISSUE THREAD

**Issue by bkleinman7** [byucs340ta/Spring2019#41]
I have no idea what some of the colors are.. I would like a drop down list when I click on a gray route.

**Comment by bryantmh** [comment]
Looks like a backend issue with startGame

**Comment by bryantmh** [comment]
Whoops, left this comment on the wrong one, haha. Should be fixed with this:
https://github.com/byucs340ta/Spring2019/issues/41 and this:
https://github.com/byucs340ta/Spring2019/issues/21
